### ISSUE TITLE
when use volcano.sh/gpu-number: 1，why the pod has all GPU？

### ISSUE THREAD

**Issue by zishen** [volcano-sh/devices#11]
Maybe a bug 

when i request i gpu for  k8s (the yaml in https://github.com/volcano-sh/devices/issues/10), I find the volcano-deviceplugin give all the node gpus to my pod.

the picture is flowed(in /dev/):
![gpu](https://user-images.githubusercontent.com/7522079/99641373-22ee6d80-2a85-11eb-93b8-3bd28e7a6155.PNG)

I donot know why

k8s:1.17.3
volcano:v1.0.1
volcano-deviceplugin:1.0.0
docker:18.06.3-ce
os : ubuntu18.04
arm : x86

**Comment by wpeng102** [comment]
Refer the GPU share user doc (https://github.com/volcano-sh/volcano/blob/master/docs/user-guide/how_to_use_gpu_sharing.md).
Currently, only support specify GPU share memory,  to specify GPU number is a limitation. We are planning a project to handle this case.

**Comment by k82cn** [comment]
@wpeng102 , please open an issue for this enhancement.

**Comment by shinytang6** [comment]
please refer to https://github.com/volcano-sh/devices/pull/15
/close
