### ISSUE TITLE
[enhance] support specify GPU number for pod resource request 

### ISSUE THREAD

**Issue by wpeng102** [volcano-sh/devices#12]
Request from https://github.com/volcano-sh/devices/issues/11

Refer the GPU share user doc (https://github.com/volcano-sh/volcano/blob/master/docs/user-guide/how_to_use_gpu_sharing.md).
Currently, only support specify GPU share memory, to specify GPU number is a limitation.

We need support `volcano.sh/gpu-number` just like nvidia gpu plugin to support specify GPU number for pod resource request

**Comment by Thor-wl** [comment]
This feature has been taken into CNCF Community Bridge.
Idea detail: https://github.com/cncf/mentoring/pull/336/files

**Comment by peiniliu** [comment]
Hi,

I would like to join the discussion and make a contribution to this topic.

**Comment by Thor-wl** [comment]
> Hi,
> 
> I would like to join the discussion and make a contribution to this topic.

Great! I've got your resume. Please provide a work plan to me and the mentor's email is wangleibo1@huawei.com

**Comment by shinytang6** [comment]
resolved by https://github.com/volcano-sh/devices/pull/15
/close
