### ISSUE TITLE
Should add volcano.sh/gpu-index annotation in pod example

### ISSUE THREAD

**Issue by zen-xu** [volcano-sh/devices#9]
I found the example missing specify `volcano.sh/gpu-index` annotation

If not specify `volcano.sh/gpu-index` annotation when want to allocate `volcano.sh/gpu-memory`, the pod will always fail to be created.

**Comment by wpeng102** [comment]
This is should share the same reason with https://github.com/volcano-sh/devices/issues/10#issuecomment-737114573
